<a href="https://colab.research.google.com/github/Ambar209/Ambar209/blob/main/Datatoolkit_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1:  Demonstrate three different methods for creating identical 2D arrays in
#     NumPy Provide the code for each method and the final output after each
#     method
#Answer:
#    Method 1: Using numpy.array()
import numpy as np

# Method 1: Using numpy.array()
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Method 1 Output:")
print(array1)
#o/p
# Method 1 Output:
# [[1 2 3]
#  [4 5 6]]



#Method 2: Using numpy.zeros()

# Method 2: Using numpy.zeros() and filling it
array2 = np.zeros((2, 3), dtype=int)
array2[0] = [1, 2, 3]
array2[1] = [4, 5, 6]
print("\nMethod 2 Output:")
print(array2)
#o/p
# Method 2 Output:
# [[1 2 3]
#  [4 5 6]]



#Method 3: Using numpy.full()
array3 = np.full((2, 3), 7)
print("\nMethod 3 Output:")
print(array3)
#o/p
#Method 3 Output:
#[[1 2 3]
 #[4 5 6]]


 #Q2:  Using the Numpy function, generate an array of wRR evenly spaced numPers
 #     Petween w and wR and Reshape that wD array into a 2D array

 #Answe:
 import numpy as np

# Define the parameters
w = 1.0  # starting value
wR = 10.0  # ending value
numPers = 9  # number of evenly spaced numbers

# Generate the 1D array of evenly spaced numbers
array_1d = np.linspace(w, wR, numPers)

# Reshape the array into a 2D array (for example, 3 rows and 3 columns)
array_2d = array_1d.reshape((3, 3))

# Print the outputs
print("1D Array:")
print(array_1d)
print("\n2D Array:")
print(array_2d)

#o/p
#1D Array:
#[ 1.   2.   3.   4.   5.   6.   7.   8.   9. ]

#2D Array:
#[[1. 2. 3.]
 #[4. 5. 6.]
 #[7. 8. 9.]]

 #Q3:   Explain the following terms
 #     The difference in np.array, np.asarray and np.asanyarray.

 #answer: 1 np.array(): Always copies data.
 #        2 np.asarray(): Copies only if the input is not already an array of the same type.
 #        3 np.asanyarray(): Like np.asarray(), but retains subclasses of ndarray.

 #         The difference between Deep copy and shallow copy

 #Answer: A shallow copy creates a new object, but it does not create copies of
 #        nested objects within the original object. Instead, it copies
 #        references to those nested objects.

 #       A deep copy creates a new object and recursively copies all nested
 #       objects, creating independent copies of them.

 #Q4:  Generate a 3x3 array with random floating-point numbers between 5 and 20
 #     then round each number in the array of 2 decimal places

 #Answer:
 import numpy as np

# Generate a 3x3 array of random floats between 5 and 20
random_array = np.random.uniform(5, 20, size=(3, 3))

# Round each number in the array to 2 decimal places
rounded_array = np.round(random_array, 2)

# Print the outputs
print("Random Array:")
print(random_array)
print("\nRounded Array:")
print(rounded_array)

#o/p
#Random Array:
#[[ 9.53 13.42 19.87]
#[ 7.05 16.32 12.56]
#[14.76  8.12  5.99]]

#Rounded Array:
#[[ 9.53 13.42 19.87]
# [ 7.05 16.32 12.56]
#[14.76  8.12  5.99]]

#Q5:  Create a NumPy array with random integers between 1 and 10 of shape (5,6)
#     after creating the array perform the following operation .
#     a  Extract all even integers from array
#     b  Extract all odd integers from array

#Answer:
import numpy as np

# Create a 5x6 array with random integers between 1 and 10
array = np.random.randint(1, 11, size=(5, 6))

# Print the original array
print("Original Array:")
print(array)

# a. Extract all even integers from the array
even_integers = array[array % 2 == 0]
print("\nEven Integers:")
print(even_integers)

# b. Extract all odd integers from the array
odd_integers = array[array % 2 != 0]
print("\nOdd Integers:")
print(odd_integers)


#o/p
#Original Array:
#[[ 6  3  4  9  7  2]
# [ 1  5 10  8  6  2]
# [ 5  7  2  3  4  8]
# [ 8  9  3  1  4  5]
# [ 7  1  5  3  2  10]]

#Even Integers:
#[ 6  4  2 10  8  6  2  2  4  8  8  4  2 10]

#Odd Integers:
#[3 9 7 1 5 5 7 3 1 9 3 5 7 1 5 3]

#Q6:  Create a 3D NumPy array of shape (3, 3, 3) containing random integers
#     between 1 and 10 Perform the following operations:

# a) Find the indices of the maximum values along each depth level (third axis).

# b) Perform element-wise multiplication of between both array

#Answer:
import numpy as np

# Create a 3D array of shape (3, 3, 3) with random integers between 1 and 10
array = np.random.randint(1, 11, size=(3, 3, 3))

# Print the original array
print("Original Array:")
print(array)

# a) Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(array, axis=2)
print("\nIndices of Maximum Values along each Depth Level:")
print(max_indices)

# b) Perform element-wise multiplication of the array with itself
multiplied_array = array * array
print("\nElement-wise Multiplication of the Array:")
print(multiplied_array)


#o/p
#Original Array:
#[[[ 3  7  8]
#  [ 1  6  5]
# [ 4  5  2]]

# [[ 2  9  8]
# [ 5  2  7]
#  [ 9  4  1]]

# [[ 5  1  3]
#  [ 7  9  3]
#  [10  5  4]]]

#Indices of Maximum Values along each Depth Level:
#[[2 0 0]
# [2 0 0]
# [2 1 0]]

#Element-wise Multiplication of the Array:
#[[[ 9 49 64]
#  [ 1 36 25]
#  [16 25  4]]

# [[ 4 81 64]
#  [25  4 49]
#  [81 16  1]]

# [[25  1  9]
#  [49 81  9]
#  [100 25 16]]]


#Q7  Clean and transform the 'Phone' column in the sample dataset to remove
#    non-numeric characters and convert it to a numeric data typeƒ Also display the
#    taPle attriPutes and data types of each column

#Answer:
import pandas as pd

# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Phone': ['+1-800-555-1234', '(555) 123-4567', '555.789.0123'],
    'Age': [25, 30, 35]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Clean and transform the 'Phone' column
df['Phone'] = df['Phone'].replace(r'\D', '', regex=True)  # Remove non-numeric characters
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')  # Convert to numeric, coerce errors

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

# Display table attributes and data types of each column
print("\nData Types:")
print(df.dtypes)


#Q8:  Perform the following tasks using people dataset:

 #   a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 #   b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 #   c) Display the first 10 rows of the filtered dataset.

#    d) Extract the ‘Salary’' column as a Series and display its last 5 values

#Answer:
import pandas as pd

# a) Read the 'data.csv' file, skipping the first 50 rows
file_path = 'data.csv'  # Update with your actual file path
df = pd.read_csv(file_path, skiprows=50)

# b) Only read specific columns: 'Last Name', 'Gender', 'Email', 'Phone', and 'Salary'
filtered_df = df[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]

# c) Display the first 10 rows of the filtered dataset
print("First 10 rows of the filtered dataset:")
print(filtered_df.head(10))

# d) Extract the 'Salary' column as a Series and display its last 5 values
salary_series = filtered_df['Salary']
print("\nLast 5 values of the Salary column:")
print(salary_series.tail(5))


#Q9:  Filter and select rows from the People Dataset, where the “Last Name'
#     column contains the name 'Duke',  'Gender' column contains the word
#     Female and ‘salary’ should be less than 85000
import pandas as pd

# Read the 'data.csv' file
file_path = 'data.csv'  # Update with your actual file path
df = pd.read_csv(file_path)

# Filter the dataset based on the conditions
filtered_df = df[
    (df['Last Name'].str.contains('Duke', case=False, na=False)) &
    (df['Gender'].str.contains('Female', case=False, na=False)) &
    (df['Salary'] < 85000)
]

# Display the filtered DataFrame
print("Filtered DataFrame:")
print(filtered_df)


#Q10:  Create a 7*5. Data frame in Pandas using a series generated from 35
#      random integers between 1 to 6 )?
#Answer:
import pandas as pd
import numpy as np

# Generate 35 random integers between 1 and 6
random_integers = np.random.randint(1, 7, size=35)

# Create a Pandas Series from the random integers
random_series = pd.Series(random_integers)

# Reshape the Series into a 7x5 DataFrame
df = random_series.values.reshape(7, 5)

# Create a DataFrame
df = pd.DataFrame(df, columns=[f'Col{i+1}' for i in range(5)])

# Display the DataFrame
print("7x5 DataFrame:")
print(df)


#Q11:  Create two different Series, each of length 50, with the following criteria:

#     a) The first Series should contain random numbers ranging from 10 to 50.

#     b) The second Series should contain random numbers ranging from 100 to 1000.

#     c) Create a Data Frame by 'joining these Series by column, and, change
#       the names of the columns to 'col1', 'col2', etc

#Answer:
import pandas as pd
import numpy as np

# a) Create the first Series with random numbers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# b) Create the second Series with random numbers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, size=50))

# c) Create a DataFrame by joining the Series and change the names of the columns
df = pd.DataFrame({
    'col1': series1,
    'col2': series2
})

# Display the DataFrame
print("DataFrame:")
print(df)


#Q12:  Perform the following operations using people data set:

#    a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

#    b) Delete the rows containing any missing values.

#   c) Print the final output also

#Answer:
import pandas as pd

# Read the 'data.csv' file
file_path = 'data.csv'  # Update with your actual file path
df = pd.read_csv(file_path)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns
df.drop(columns=['Email', 'Phone', 'Date of birth'], inplace=True)

# b) Delete the rows containing any missing values
df.dropna(inplace=True)

# d) Print the final output
print("\nFinal DataFrame after deletions:")
print(df)


#Q13:  Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
#      following tasks using Matplotlib and NumPy:

#  a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.

#  b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

#  c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

#  d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

#  e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

#  f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

#Answer:
import numpy as np
import matplotlib.pyplot as plt

# Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# a) Create a scatter plot
plt.scatter(x, y, color='red', marker='o', label='Data Points')

# b) Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# c) Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# d) Label the x-axis and y-axis
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# e) Set the title of the plot
plt.title('Advanced Scatter Plot of Random Values')

# f) Display a legend
plt.legend()

# Show the plot
plt.show()


#Q14:  Create a time-series dataset in a Pandas Data Frame with columns: 'Date',
#     'Temperature', 'Humidity' and
#      Perform the following tasks using Matplotlib
#   a) Plot the 'Temperature' and 'Humidity' on the same plot with different
#      y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity').

#   b) Label the x-axis as 'Date'.

#   c) Set the title of the plot as 'Temperature and Humidity Over Time'.

#Answer:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create a date range
date_range = pd.date_range(start='2023-01-01', periods=100, freq='D')

# Create random temperature and humidity data
temperature = np.random.uniform(low=15, high=35, size=len(date_range))  # Temperatures between 15 and 35
humidity = np.random.uniform(low=30, high=90, size=len(date_range))      # Humidity between 30% and 90%

# Create a DataFrame
data = pd.DataFrame({
    'Date': date_range,
    'Temperature': temperature,
    'Humidity': humidity
})

# Plotting
fig, ax1 = plt.subplots()

# a) Plot Temperature
ax1.plot(data['Date'], data['Temperature'], color='red', label='Temperature', marker='o')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (°C)', color='red')
ax1.tick_params(axis='y', labelcolor='red')

# Create a second y-axis for Humidity
ax2 = ax1.twinx()
ax2.plot(data['Date'], data['Humidity'], color='blue', label='Humidity', marker='x')
ax2.set_ylabel('Humidity (%)', color='blue')
ax2.tick_params(axis='y', labelcolor='blue')

# b) Set the title of the plot
plt.title('Temperature and Humidity Over Time')

# Show the plot
plt.show()


#Q15:  Create a NumPy array data containing 1000 samples from a normal
#      distribution. Perform the following tasks using Matplotlib

# a) Plot a histogram of the data with 30 bins.

# b) Overlay a line plot representing the normal distribution's probability density function (PDF).

# c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

# d) Set the title of the plot as 'Histogram with PDF Overlay

#Answer:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)  # mean = 0, std dev = 1

# a) Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', label='Histogram')

# b) Overlay a line plot for the normal distribution's PDF
xmin, xmax = plt.xlim()  # Get the limits of x-axis
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of normal distribution
plt.plot(x, p, 'k', linewidth=2, label='PDF')

# c) Label the axes
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')

# d) Set the title of the plot
plt.title('Histogram with PDF Overlay')

# Display legend
plt.legend()

# Show the plot
plt.show()


#Q16:  Set the title of the plot as 'Histogram with PDF Overlay'.
#Answer:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Create a NumPy array with 1000 samples from a normal distribution
data = np.random.normal(loc=0, scale=1, size=1000)  # mean = 0, std dev = 1

# a) Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, alpha=0.6, color='g', label='Histogram')

# b) Overlay a line plot for the normal distribution's PDF
xmin, xmax = plt.xlim()  # Get the limits of x-axis
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, loc=0, scale=1)  # PDF of normal distribution
plt.plot(x, p, 'k', linewidth=2, label='PDF')

# c) Label the axes
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')

# d) Set the title of the plot
plt.title('Histogram with PDF Overlay')

# Display legend
plt.legend()

# Show the plot
plt.show()


#Q17:  Create a Seaborn scatter plot of two random arrays, color points based
#      on their position relative to the origin (quadrants), add a legend, label
#      the axes, and set the title as 'Quadrant-wise Scatter Plot'.
#Answer:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Generate two random arrays
np.random.seed(42)  # For reproducibility
x = np.random.randn(100)
y = np.random.randn(100)

# Create a DataFrame to hold the data
data = pd.DataFrame({'x': x, 'y': y})

# Determine the quadrant for each point
data['Quadrant'] = np.where((data['x'] >= 0) & (data['y'] >= 0), 'Quadrant 1',
                    np.where((data['x'] < 0) & (data['y'] >= 0), 'Quadrant 2',
                    np.where((data['x'] < 0) & (data['y'] < 0), 'Quadrant 3',
                              'Quadrant 4'))))

# Create a Seaborn scatter plot
plt.figure(figsize=(10, 6))
scatter = sns.scatterplot(data=data, x='x', y='y', hue='Quadrant', palette='Set1')

# Customize the plot
plt.title('Quadrant-wise Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend(title='Quadrants')

# Show the plot
plt.grid()
plt.show()


#Q18:  With Bokeh, plot a line chart of a sine wave function, add grid lines,
#      label the axes, and set the title as 'Sine Wave Function'
#Answer:
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

# Use this if you're running in a Jupyter notebook
output_notebook()

# Generate x values
x = np.linspace(0, 2 * np.pi, 100)  # 100 points from 0 to 2π
y = np.sin(x)  # Calculate the sine of x

# Create a new figure
p = figure(title='Sine Wave Function', x_axis_label='X values (radians)', y_axis_label='Sine values')

# Add a line renderer
p.line(x, y, legend_label='Sine wave', line_width=2, color='blue')

# Add grid lines
p.grid.grid_line_color = 'gray'
p.grid.grid_line_alpha = 0.5

# Show the plot
show(p)


#Q19:  Using Bokeh, generate a bar chart of randomly generated categorical data,
#      color bars based on their values, add hover tooltips to display exact
#      values, label the axes, and set the title as 'Random Categorical Bar Chart

#Answer:
import numpy as np
import pandas as pd
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.transform import factor_cmap

# Generate random categorical data
categories = [f'Category {i}' for i in range(1, 11)]
values = np.random.randint(1, 100, size=len(categories))

# Create a DataFrame for easier handling
data = pd.DataFrame({'Category': categories, 'Values': values})

# Create a ColumnDataSource from the DataFrame
source = ColumnDataSource(data)

# Define a color palette based on values
colors = ['#1f77b4' if v < 50 else '#ff7f0e' for v in values]

# Create the figure
p = figure(x_range=categories, plot_height=400, title="Random Categorical Bar Chart",
           toolbar_location=None, tools="")

# Add bars to the figure
p.vbar(x='Category', top='Values', width=0.9, source=source,
       line_color="white", fill_color=factor_cmap('Values', palette=colors, factors=values))

# Add hover tooltips
hover = HoverTool()
hover.tooltips = [("Category", "@Category"), ("Value", "@Values")]
p.add_tools(hover)

# Label the axes
p.xaxis.axis_label = "Categories"
p.yaxis.axis_label = "Values"
p.xaxis.major_label_orientation = "vertical"

# Customize the layout
p.y_range.start = 0
p.y_range.end = max(values) + 10

# Show the plot
show(p)


#Q20:  Using  Plotly,  create a basic line plot of a randomly generated dataset,
#     label the axes, and set the title as 'Simple Line Plot'

#Answer:
import numpy as np
import plotly.graph_objects as go

# Generate random data
np.random.seed(0)  # For reproducibility
x = np.linspace(0, 10, 100)
y = np.random.random(100)

# Create the line plot
fig = go.Figure()

fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='Random Data'))

# Update layout
fig.update_layout(
    title='Simple Line Plot',
    xaxis_title='X Axis Label',
    yaxis_title='Y Axis Label'
)

# Show the plot
fig.show()


#Q21:  Using Plotly, create an interactive pie chart of randomly generated data,
#      add labels and percentages, set the title as 'Interactive Pie Chart'

#Answer:
import numpy as np
import plotly.graph_objects as go

# Generate random data
np.random.seed(0)  # For reproducibility
labels = [f'Category {i+1}' for i in range(10)]
values = np.random.randint(1, 100, size=len(labels))

# Create the pie chart
fig = go.Figure(data=[go.Pie(
    labels=labels,
    values=values,
    textinfo='label+percent',  # Show both label and percentage
    hoverinfo='label+percent',  # Show both label and percentage on hover
)])

# Update layout
fig.update_layout(title='Interactive Pie Chart')

# Show the plot
fig.show()

