<a href="https://colab.research.google.com/github/Ambar209/Ambar209/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1:   Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Answer: NumPy is a powerful library for numerical computing in Python, and it offers several key advantages:

Numerical Computation: NumPy provides support for large, multi-dimensional arrays and matrices, along with a variety of mathematical functions to operate on these data structures.

Advantages

Performance
Convenient Syntax
Broad Functionality
Interoperability
Memory Efficiency

Q2:  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Answer: Both np.mean() and np.average() are used to calculate the average of elements in a NumPy array, but they have some differences in functionality and use cases.

Q3:  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

Answer:

 Reversing a 1D Array
For a 1D array, you can reverse it by using slicing with a step of -1.

In [ ]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = array_1d[::-1]

print(reversed_1d)  # Output: [5 4 3 2 1]


For a 2D array, you can reverse it along different axes using slicing.

In [ ]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = array_2d[::-1]

# Reverse along the second axis (columns)
reversed_columns = array_2d[:, ::-1]

print("Original 2D array:\n", array_2d)
print("Reversed along rows:\n", reversed_rows)
print("Reversed along columns:\n", reversed_columns)


Q4:   How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance

Answer:
You can determine the data type of elements in a NumPy array using the .dtype attribute. Here's how you can do it.


In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3.5, 4])

# Check the data type
data_type = array.dtype

print(data_type)  # Output: float64


Importance of Data Types in NumPy
Memory Management:
Performance:
Type-Safety:


Q5:   Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer: ndarrays (N-dimensional arrays) are the core data structure in NumPy. They are powerful, multi-dimensional arrays that allow for efficient storage and manipulation of numerical data.

Key Features of ndarrays:

Homogeneous Data
N-Dimensional
Shape and Size
ectorized Operations
Performance


Q6:  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer:
      NumPy arrays provide substantial performance benefits over Python lists for large-scale numerical operations due to their efficient memory layout, data type homogeneity, support for vectorization and broadcasting, optimized performance libraries, reduced overhead, and compatibility with parallel processing.

Q7:   Compare vstack() and hstack() functions in NumPy. Provide examples
      demonstrating their usage and output.

Answer:
      vstack() Function

In [ ]:
import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using vstack to stack arrays vertically
result_vstack = np.vstack((a, b))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[1 2 3]
 [4 5 6]]


hstack() Function

In [ ]:
import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using hstack to stack arrays horizontally
result_hstack = np.hstack((a, b))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[1 2 3 4 5 6]


Q8:  Explain the differences between fliplr() and flipud() methods in NumPy,
     including their effects on various array dimensions.

Answer:
      fliplr(): Flips arrays left to right, affecting the order of columns. Mostly used for 2D arrays.
      flipud(): Flips arrays up to down, affecting the order of rows. Also mostly used for 2D arrays.

Q9: Discuss the functionality of the array_split() method in NumPy. How does    it  handle uneven splits?

Answer:
      array_split() is a versatile function for dividing arrays into multiple sub-arrays.
      It can handle uneven splits by distributing elements as evenly as possible among the resulting sub-arrays.

Q10:  Explain the concepts of vectorization and broadcasting in NumPy. How do
      they contribute to efficient array operations?

Answer:
      Vectorization allows for operations on entire arrays without explicit loops, improving speed and code clarity.
      roadcasting enables operations between arrays of different shapes by automatically aligning them, enhancing flexibility and memory efficiency.



PRACTICAL QUESTIONS:-

Q1:   Create a 3x3 NumPy array with random integers between 1 and 100. Then,
      interchange its rows and columns

Answer:
      

In [ ]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array_3x3)

# Interchanging rows and columns (transposing the array)
transposed_array = array_3x3.T

print("\nTransposed Array:")
print(transposed_array)


#Original Array:
[[23 45 12]
 [67 89 34]
 [56 78 91]]

#Transposed Array:
[[23 67 56]
 [45 89 78]
 [12 34 91]]


#Q2:  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array,
#      then into a 5x2 array.
#Answer:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This will create an array with values from 0 to 9

print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


#Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

#Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

#Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#Q3:  Create a 4x4 NumPy array with random float values. Add a border of zeros
#a    round it, resulting in a 6x6 array
#Answer:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant',
                           constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


#Original 4x4 Array:
[[0.12345678 0.23456789 0.34567891 0.45678912]
 [0.56789123 0.67891234 0.78912345 0.89123456]
 [0.91234567 0.12345678 0.23456789 0.34567891]
 [0.45678912 0.56789123 0.67891234 0.78912345]]

#6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.12345678 0.23456789 0.34567891 0.45678912 0.         0.        ]
 [0.56789123 0.67891234 0.78912345 0.89123456 0.         0.        ]
 [0.91234567 0.12345678 0.23456789 0.34567891 0.         0.        ]
 [0.45678912 0.56789123 0.67891234 0.78912345 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#Q4: Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#Answer:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


#Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


#Q5: Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply
#    different case transformations
#    (uppercase, lowercase, title case, etc.) to each element.
#Answer:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

# Display the results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalized:")
print(capitalize_array)


#Original Array:
['python' 'numpy' 'pandas']

#Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

#Lowercase:
['python' 'numpy' 'pandas']

#Title Case:
['Python' 'Numpy' 'Pandas']

#Capitalized:
['Python' 'Numpy' 'Pandas']


#Q6:  Generate a NumPy array of words. Insert a space between each character
#     of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'numpy', 'array', 'transform'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Display the results
print("Original Array of Words:")
print(words_array)

print("\nWords with Spaces Between Characters:")
print(spaced_words_array)


#Original Array of Words:
['hello' 'numpy' 'array' 'transform']

#Words with Spaces Between Characters:
['h e l l o' 'n u m p y' 'a r r a y' 't r a n s f o r m']


#Q7:  Create two 2D NumPy arrays and perform element-wise addition, subtraction,
#     multiplication, and division.
#Answer:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)



#Array 1:
 ["[1 2 3]"
 "[4 5 6]"]

#Array 2:
["[ 7  8  9]"
 "[10 11 12]"]

#Element-wise Addition:
["[ 8 10 12]"
 "[14 16 18]"]

#Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

#Element-wise Multiplication:
["[ 7 16 27]"
 "[40 55 72]"]

#Element-wise Division:
["[0.14285714 0.25       0.33333333]"
 "[0.4        0.45454545 0.5       ]"]


#Q8:   Use NumPy to create a 5x5 identity matrix, then extract its diagonal
#      elements.
#Answer:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


#5x5 Identity Matrix:
["[1. 0. 0. 0. 0.]"
 "[0. 1. 0. 0. 0.]"
 "[0. 0. 1. 0. 0.]"
 "[0. 0. 0. 1. 0.]"
 "[0. 0. 0. 0. 1.]"]

#Diagonal Elements:
"[1. 1. 1. 1. 1.]"


#Q9:  Generate a NumPy array of 100 random integers between 0 and 1000. Find
#     and display all prime numbers in this array.
#Answer:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers Array:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


#Random Integers Array:
"[403 211 790 971 762 633 849 211 859 732 ...]"  # Example random integers

#Prime Numbers in the Array:
[211, 971, 859, ...]  # Example prime numbers found

#Q10:   Create a NumPy array representing daily temperatures for a month.
#       Calculate and display the weekly averages.
#Answer:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Let's assume temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=30)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Calculate weekly averages
# Reshape the array into 4 weeks (4 rows) and 7 days (7 columns)
# Note: We'll assume the last week has fewer days if needed
weekly_averages = []

# Calculate averages for the first 4 full weeks (28 days)
for i in range(0, 28, 7):
    weekly_avg = daily_temperatures[i:i+7].mean()
    weekly_averages.append(weekly_avg)

# Handle the last 2 days (if any)
if len(daily_temperatures) > 28:
    last_week_avg = daily_temperatures[28:].mean()
    weekly_averages.append(last_week_avg)

print("\nWeekly Averages:")
print(weekly_averages)


#Daily Temperatures for the Month:
[20 23 27 31 22 19 18 34 29 25 28 30 17 15 33 26 35 21 24 29 22 26 15 18 30 32
 27 25 19 34 21 35 24]

#Weekly Averages:
[23.428571428571427, 26.285714285714285, 21.285714285714285, 24.5]

